authentication/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', include('login.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from . import views
from .views import Author

urlpatterns = [
    path("article-<int:article_id>", Author.as_view, name="articles")
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('signin', views.signin, name="connection"),
    path('signup', views.signup, name="register"),
    path('disconnect', views.disconnect, name="disconnect"),
    path('profile', views.profile, name="profile")
]

blog/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    article_numbers = models.IntegerField(default=0, blank=True, null=True)

login/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=25, unique=True, blank=False)


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, default="1")
    name = models.CharField(max_length=255, default="1")
    avatar = models.ImageField(upload_to="login/static/profile_images", blank=True, null=True)

authentication/views.py
from django.shortcuts import render


def index(request):
    return render(request, "home/index.html")

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView



class Author(TemplateView):
    template_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


class Articles(TemplateView):
    template_name = "articles"

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, get_user_model
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .models import CustomUser


def signin(request):
    form = AuthenticationForm
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("login:profile")
        else:
            messages.info(request, "login ou mot de passe incorrect !")
            return redirect("login:connection")

    return render(request, "login_views/login.html", context={"form": form})


def signup(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password != password2:
            return render(request, "login_views/signup.html", context={'error': "Nom d'utilisateur ou mot de passe incorrect"})
        user = CustomUser.objects.create_user(username=username, password=password, email=email)
        login(request, user)
        return redirect("login:profile")
    return render(request, 'login_views/signup.html')





def disconnect(request):
    logout(request)
    messages.info(request, "Vous êtes déconnecté !")
    return redirect("home")


def profile(request):
    return render(request, "login_views/profile.html")

authentication/templates/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    {% block style %}
    <script src="{% static 'css/style.css' %}"></script>
    {% endblock %}
     {% tailwind_css %}
</head>
<body class="bg-gradient-to-r from-sky-300 to-indigo-900">
<div class="border border-b-8 border-t-0 border-x-0 border-indigo-900 p-4 bg-gradient-to-l from-sky-300 to-indigo-900 text-white">
    <h1 class="text-3xl text-center mb-8 mt-8 rounded p-4 bg-gradient-to-l from-indigo-900 to-sky-300 w-1/2 m-auto">Blog Sur Python - Django et son Authentification</h1>
        <div class="flex justify-center items-center w-full">
            <a class="text-2xl mx-5" href="{% url 'home' %}">Accueil</a>
            {% if user.is_authenticated %}
                <div>
                    <a class="w-full flex flex-row justify-center text-md mx-5 " href="{% url 'login:disconnect' %}">Se déconnecter</a>
                </div>
            {% else %}
                <div class="flex flex-row items-center">
                 <a class="text-lg mx-5" href="{% url 'login:connection' %}">Connexion</a>
                <p class="text-lg"> | </p>
                <a class="text-lg mx-5 " href="{% url 'login:register' %}">S'inscrire</a>
            </div>
            {% endif %}
            <hr>
        </div>

</div>
{% block body%}



{% endblock %}
</body>
</html>

authentication/templates/home/index.html
{% extends '../base.html' %}

{% block body%}
    <h1 class="flex flex-row justify-center items-center text-4xl m-5">Accueil</h1>
{% endblock %}

blog/templates/blog_views/articles.html
{% extends '../base.html' %}

{% block body %}
<h1>Welcome to Articles page </h1>
<article>

    <h3>Débuter avec Django</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, deleniti distinctio dolor eum hic laborum nemo placeat quod sed tempore? Alias amet consequatur ea fugit ipsam nesciunt non optio veniam.</p>

</article>

{% endblock %}

login/templates/login_views/login.html
{% extends '../base.html' %}
{% load static %}
{% static 'login_views/style.css' %}

{% block body%}
    <h1 class="text-center m-5 text-4xl" id="title">Connexion utilisateur</h1>
    <form id="form" class="px-4 py-3 flex flex-col justify-center items-center text-black" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="m-2 border border-2 border-black rounded w-40 m-auto bg-blue-800 text-white pt-2 pb-2" type="submit" value="Submit">Se connecter</button>
    </form>

    {% for message in messages %}
    <ul class="list-none">
        <li class="text-xl text-yellow-400 bg-red-600 w-1/2 m-auto text-center rounded">{{message}}</li>
    </ul>
    {% endfor%}
{% endblock %}

login/templates/login_views/profile.html
{% extends '../base.html' %}

{% block body%}
<div class="flex flex-col justify-evenly items-center text-2xl m-5">
    <h1 class="text-4xl">Bienvenue sur votre profile</h1>

 {% if user.is_authenticated %}
    <div class="m-4 text-red-400 font-bold text-xs p-2 border border-white border-3 rounded bg-indigo-900">
        <span class="text-white">
            {{ user.username }} :
        </span> is connected
    </div>


    {% endif %}
</div>
{% endblock%}

login/templates/login_views/signup.html
{% extends '../base.html'%}

{% block body%}
    <h1>Signup</h1>
    <form id="signup_form" class="px-4 py-3 flex flex-col justify-between items-center text-black" method="post">
        {% csrf_token %}
        <label for="id_username" id="label_username">Nom d'utilisateur</label>
        <input type="text" name="username" id="id_username">
        <label for="email" id="label_email">Email</label>
        <input type="email" name="email" id="email">
        <label for="id_password1" id="label_password1">Mot de passe</label>
        <input type="text" name="password1" id="id_password1">
        <label for="id_password2" id="label_password2">Mot de passe</label>
        <input type="text" name="password2" id="id_password2">
        <input class="border border-2 border-black rounded w-40 m-auto bg-blue-800 text-white pt-2 pb-2" type="submit" value="S'inscrire">
    </form>

    {% if error %}
    <div class="w-full">
        <small class="text-center text-red-600">{{error}}</small>
    </div>
    {% endif %}

{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>